-- Isolated storage fixture only; no Production credentials or data.
create schema auth; create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$; create function public.is_active_operation_member() returns boolean language sql stable as $$select auth.uid() is not null$$;
create table public.entity_audit_events("id" uuid,"module_code" text,"entity_type" text,"entity_id" uuid,"action" text,"before_data" jsonb,"after_data" jsonb,"changed_by" uuid,"change_reason" text,"request_id" uuid,"created_at" timestamp with time zone);
create table public.family_booking_members("id" uuid,"family_booking_id" uuid,"stable_member_key" text,"dog_id" uuid,"service_type" text,"status" text,"hotel_stay_id" uuid,"operation_schedule_id" uuid,"shared_room_group_id" uuid,"version" integer,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text);
create table public.family_shared_room_groups("id" uuid,"family_booking_id" uuid,"stable_group_key" text,"leader_member_id" uuid,"room_type_id" uuid,"normalized_starts_at" timestamp with time zone,"normalized_ends_at" timestamp with time zone,"requested_capacity" integer,"status" text,"version" integer,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text);
create table public.hotel_capacity_reservations("id" uuid,"source_kind" text,"hotel_stay_id" uuid,"daycare_schedule_id" uuid,"room_type_id" uuid,"reserved_from" timestamp with time zone,"reserved_until" timestamp with time zone,"quantity" smallint,"version" integer,"request_id" uuid,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text,"physical_occupancy_id" uuid,"shared_room_group_id" uuid);
create table public.hotel_physical_occupancies("id" uuid,"family_booking_id" uuid,"shared_room_group_id" uuid,"customer_id" uuid,"room_type_id" uuid,"room_id" uuid,"occupied_from" timestamp with time zone,"occupied_until" timestamp with time zone,"restore_occupied_until" timestamp with time zone,"capacity_reservation_id" uuid,"room_allocation_id" uuid,"status" text,"version" integer,"request_id" uuid,"canonical_payload_hash" text,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"completed_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text);
create table public.hotel_physical_occupancy_members("id" uuid,"occupancy_id" uuid,"family_booking_member_id" uuid,"hotel_stay_id" uuid,"dog_id" uuid,"status" text,"joined_at" timestamp with time zone,"left_at" timestamp with time zone,"version" integer,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text);
create table public.hotel_physical_occupancy_requests("request_id" uuid,"occupancy_id" uuid,"operation_kind" text,"canonical_payload_hash" text,"response" jsonb,"created_by" uuid,"created_at" timestamp with time zone,"completed_at" timestamp with time zone);
create table public.hotel_room_allocations("id" uuid,"capacity_reservation_id" uuid,"room_id" uuid,"allocated_from" timestamp with time zone,"allocated_until" timestamp with time zone,"assignment_reason" text,"version" integer,"request_id" uuid,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text);
create table public.hotel_stays("id" uuid,"dog_id" uuid,"checked_in_at" timestamp with time zone,"checked_in_by" uuid,"checked_out_at" timestamp with time zone,"checked_out_by" uuid,"checkout_previous_reserved_until" timestamp with time zone,"checkout_previous_allocation_id" uuid,"checkout_previous_allocation_until" timestamp with time zone,"version" integer,"request_id" uuid,"created_by" uuid,"created_at" timestamp with time zone,"updated_by" uuid,"updated_at" timestamp with time zone,"archived_at" timestamp with time zone,"archived_by" uuid,"archive_reason" text);
create table public.dogs(id uuid,name text);
create table public.hotel_rooms(id uuid,name text,room_type_id uuid);
create table public.hotel_room_types(id uuid,name text);
create table public.hotel_stay_schedule_events(id uuid,hotel_stay_id uuid,operation_schedule_id uuid,event_kind text,archived_at timestamptz);
create table public.operation_schedules(id uuid,starts_at timestamptz,archived_at timestamptz);
