// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {MemoryRouter} from 'react-router-dom';
import {NotificationSession} from './NotificationProvider';
import {NotificationBell} from './NotificationUi';
import {emptyInbox,type Notice,type NotificationRepository} from './notificationRepository';
vi.mock('../lib/supabase',()=>({supabase:{}}));
vi.mock('../taskRequests/useTaskAccess',()=>({useTaskAccess:()=>({enabled:true,loading:false})}));
afterEach(()=>{cleanup();vi.useRealTimers();});
const notice=(id:string,read=false):Notice=>({id,announcement_id:null,category:'SCHEDULE',deep_link_type:'SCHEDULE_DAY',deep_link_id:'00000000-0000-4000-8000-000000000001',schedule_local_date:'2026-10-09',title:`알림 ${id}`,message:'내용',priority:'NORMAL',ack_required:false,created_at:'2026-10-09T00:00:00Z',read_at:read?'read':null,acknowledged_at:null,popup_presented_at:null,revoked_at:null,expires_at:null});
function setup(count=1){
 let rows=[notice('cached-read',true),...Array.from({length:count},(_,i)=>notice(String(i)))];let revision=()=>{};
 const repo={inbox:vi.fn(async(offset=0,unread=false)=>({...emptyInbox,items:(unread?rows.filter(n=>!n.read_at):rows).slice(offset,offset+50),unread_count:rows.filter(n=>!n.read_at).length})),subscribe:vi.fn((_id,cb)=>{revision=cb;return()=>{};}),readAll:vi.fn(async()=>{const count=rows.filter(n=>!n.read_at).length;rows=rows.map(n=>({...n,read_at:n.read_at??'read'}));return count;})} as unknown as NotificationRepository;
 render(<MemoryRouter><NotificationSession userId="self" repository={repo}><NotificationBell/></NotificationSession></MemoryRouter>);
 return {repo,revision:()=>revision(),add:()=>rows.push(notice('new'))};
}
async function open(){fireEvent.click(await screen.findByRole('button',{name:/알림센터, 읽지 않은/}));await waitFor(()=>expect(screen.queryByText('알림을 불러오는 중입니다.')).toBeNull());}
it('fresh session defaults to authoritative unread and never borrows all-page cache',async()=>{const x=setup();await open();expect(screen.getByRole('button',{name:'읽지 않음 1'}).getAttribute('aria-pressed')).toBe('true');expect(x.repo.inbox).toHaveBeenCalledWith(0,true);expect(screen.queryByRole('button',{name:/알림 cached-read/})).toBeNull();expect(screen.getByRole('button',{name:/알림 0/})).toBeTruthy();});
it('explicit all history survives close/reopen and retains read rows',async()=>{setup();await open();fireEvent.click(screen.getByRole('button',{name:'전체 기록'}));expect(await screen.findByRole('button',{name:/알림 cached-read/})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'닫기'}));await open();expect(screen.getByRole('button',{name:'전체 기록'}).getAttribute('aria-pressed')).toBe('true');});
it('zero unread has correct empty state and disables bulk read',async()=>{setup(0);await open();expect(screen.getByText('새로운 알림이 없습니다.')).toBeTruthy();expect((screen.getByRole('button',{name:'모두 읽음'}) as HTMLButtonElement).disabled).toBe(true);});
it('120 unread pages use server count and bulk command is not page-limited; badge and all history refresh',async()=>{const x=setup(120);await open();fireEvent.click(screen.getByRole('button',{name:'다음 알림'}));await screen.findByRole('button',{name:/알림 50 /});fireEvent.click(screen.getByRole('button',{name:'다음 알림'}));await screen.findByRole('button',{name:/알림 100 /});expect((screen.getByRole('button',{name:'다음 알림'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'모두 읽음'}));await screen.findByText('새로운 알림이 없습니다.');expect(x.repo.readAll).toHaveBeenCalledTimes(1);await screen.findByRole('button',{name:'알림센터, 읽지 않은 알림 0개'});fireEvent.click(screen.getByRole('button',{name:'전체 기록'}));expect(await screen.findByRole('button',{name:/알림 cached-read/})).toBeTruthy();});
it('duplicate click is blocked and failed command preserves rows/filter and allows retry',async()=>{const x=setup();await open();let reject!:(e:Error)=>void;vi.mocked(x.repo.readAll).mockReturnValue(new Promise((_,r)=>{reject=r;}));const b=screen.getByRole('button',{name:'모두 읽음'});fireEvent.click(b);fireEvent.click(b);expect(x.repo.readAll).toHaveBeenCalledTimes(1);await act(async()=>reject(Error('연결 실패')));await screen.findByText('연결 실패');expect(screen.getByRole('button',{name:/알림 0/})).toBeTruthy();expect((screen.getByRole('button',{name:'모두 읽음'}) as HTMLButtonElement).disabled).toBe(false);});
it.each(['focus','visibilitychange','revision'])('%s background refresh updates authoritative unread without clearing cached rows',async kind=>{const x=setup();await open();vi.useFakeTimers();x.add();expect(screen.getByRole('button',{name:/알림 0/})).toBeTruthy();if(kind==='revision')x.revision();else if(kind==='poll')await act(async()=>vi.advanceTimersByTimeAsync(30000));else fireEvent(kind==='focus'?window:document,new Event(kind));await act(async()=>vi.advanceTimersByTimeAsync(180));expect(screen.getByRole('button',{name:'알림센터, 읽지 않은 알림 2개'})).toBeTruthy();expect(screen.getByRole('button',{name:/알림 new/})).toBeTruthy();});

it('30 second polling refreshes unread server count',async()=>{vi.useFakeTimers();const x=setup();await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:/알림센터, 읽지 않은/}));await act(async()=>{});x.add();await act(async()=>vi.advanceTimersByTimeAsync(30180));expect(screen.getByRole('button',{name:'알림센터, 읽지 않은 알림 2개'})).toBeTruthy();expect(screen.getByRole('button',{name:/알림 new/})).toBeTruthy();});

it('a notification arriving after bulk target capture remains unread and appears after refresh',async()=>{const x=setup();await open();const original=vi.mocked(x.repo.readAll).getMockImplementation()!;let release!:(n:number)=>void;vi.mocked(x.repo.readAll).mockImplementation(async()=>{const count=await original();return new Promise<number>(r=>{release=()=>r(count);});});fireEvent.click(screen.getByRole('button',{name:'모두 읽음'}));await act(async()=>{});x.add();await act(async()=>release(1));await screen.findByRole('button',{name:'알림센터, 읽지 않은 알림 1개'});expect(await screen.findByRole('button',{name:/알림 new/})).toBeTruthy();expect(screen.queryByRole('button',{name:/알림 0/})).toBeNull();});
