// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {MemoryRouter} from 'react-router-dom';
import {PaymentDetail} from './PaymentDetail';
import {RequestHubWorkspace} from './RequestHubWorkspace';
import {emptyPaymentAccess,type PaymentDetail as Detail} from './paymentRequestTypes';
import {PaymentFailure,type PaymentRepository} from './paymentRequestRepository';
const mocks=vi.hoisted(()=>({list:vi.fn(),detail:vi.fn(),command:vi.fn()}));
vi.mock('./paymentRequestRepository',async original=>({...await original<typeof import('./paymentRequestRepository')>(),paymentRequestRepository:mocks}));
vi.mock('../lib/supabase',()=>({supabase:{rpc:vi.fn()}}));
afterEach(()=>{cleanup();vi.clearAllMocks();});
const base:Detail={id:'one',request_type:'PAYMENT_CONFIRMATION_REQUEST',payer_name:'테스트 입금자',reported_amount:10000,dog_name:'테스트',note:'확인 부탁드립니다.',status:'NOT_FOUND',version:2,requester_name:'요청자',handler_name:'담당자',can_process:false,can_cancel:true,can_edit:true,can_delete:true};
function repo(){return {command:vi.fn().mockResolvedValue({id:'one',status:'REQUESTED',version:3})}as unknown as PaymentRepository;}
it('NOT_FOUND reviewer can confirm without another negative action',async()=>{const r=repo();render(<PaymentDetail item={{...base,can_process:true,can_cancel:false,can_edit:false,can_delete:false}} repository={r} onRefresh={async()=>{}}/>);expect(screen.getByText('입금 미확인')).toBeTruthy();expect(screen.queryByRole('button',{name:'입금 미확인'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'입금 확인'}));await waitFor(()=>expect(r.command).toHaveBeenCalledWith(expect.objectContaining({action:'CONFIRMED',version:2})));});
it('requester edit preserves handler contract and sends exact editable payload',async()=>{const r=repo();render(<PaymentDetail item={base} repository={r} onRefresh={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'수정'}));fireEvent.change(screen.getByLabelText('입금자명'),{target:{value:'수정 입금자'}});fireEvent.change(screen.getByLabelText('확인 금액'),{target:{value:'20000'}});fireEvent.click(screen.getByRole('button',{name:'수정 저장'}));await waitFor(()=>expect(r.command).toHaveBeenCalledWith(expect.objectContaining({action:'UPDATED',version:2,payload:{payer_name:'수정 입금자',reported_amount:20000,dog_name:'테스트',note:'확인 부탁드립니다.'}})));});
it('delete requires explicit confirmation and returns to list only after success',async()=>{const r=repo(),done=vi.fn();render(<PaymentDetail item={base} repository={r} onRefresh={async()=>{}} onDeleted={done}/>);fireEvent.click(screen.getByRole('button',{name:'삭제'}));expect(r.command).not.toHaveBeenCalled();expect(screen.getByText(/삭제 후 일반 요청 목록에서는 보이지 않습니다/ )).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'요청 삭제'}));await waitFor(()=>expect(done).toHaveBeenCalledOnce());expect(r.command).toHaveBeenCalledWith(expect.objectContaining({action:'DELETED',payload:{},version:2}));});
it('ambiguous edit retries exact immutable request; double click single command',async()=>{const r=repo();vi.mocked(r.command).mockRejectedValueOnce(new PaymentFailure('연결 확인 필요',false));render(<PaymentDetail item={base} repository={r} onRefresh={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'수정'}));fireEvent.doubleClick(screen.getByRole('button',{name:'수정 저장'}));fireEvent.click(screen.getByRole('button',{name:'수정 저장'}));await screen.findByText('연결 확인 필요');const first=vi.mocked(r.command).mock.calls[0][0];fireEvent.click(screen.getByRole('button',{name:'같은 요청으로 결과 확인'}));await waitFor(()=>expect(r.command).toHaveBeenCalledTimes(2));expect(vi.mocked(r.command).mock.calls[1][0]).toEqual(first);});
it('confirmed viewer has no edit/delete CTA',()=>{render(<PaymentDetail item={{...base,status:'CONFIRMED',can_edit:false,can_delete:false,can_cancel:false}} onRefresh={async()=>{}}/>);expect(screen.queryByRole('button',{name:'수정'})).toBeNull();expect(screen.queryByRole('button',{name:'삭제'})).toBeNull();});
function hub(path:string){return render(<MemoryRouter initialEntries={[path+(path.includes('?')?'&':'?')+'paymentView=list']}><RequestHubWorkspace userId="self" taskAccess={{enabled:true,can_create:false,owner:false}} paymentAccess={{...emptyPaymentAccess,confirmation_enabled:true}} revision={0}/></MemoryRouter>);}
it('detail refresh preserves exact DOM nodes and permanent status slot; failure keeps content',async()=>{mocks.detail.mockResolvedValue(base);hub('/operations/requests?type=PAYMENT_CONFIRMATION_REQUEST&request=one');const heading=await screen.findByRole('heading',{name:'테스트 입금자'}),slot=screen.getByRole('status');let reject!:(e:Error)=>void;mocks.detail.mockImplementationOnce(()=>new Promise((_,r)=>{reject=r;}));fireEvent(window,new Event('focus'));expect(screen.getByRole('heading',{name:'테스트 입금자'})).toBe(heading);expect(screen.getByRole('status')).toBe(slot);expect(slot.textContent).toBe('업데이트 중');await act(async()=>reject(new Error('연결 오류')));expect(screen.getByRole('heading',{name:'테스트 입금자'})).toBe(heading);expect(screen.getByRole('status')).toBe(slot);expect(slot.textContent).toBe('');});
it('same-query list survives refresh errors',async()=>{mocks.list.mockResolvedValue({count:1,items:[{...base,display_title:'보존할 요청',lifecycle:'OPEN',counterparty:'담당자'}]});hub('/operations/requests');const row=await screen.findByText('보존할 요청');mocks.list.mockRejectedValueOnce(new Error('목록 오류'));fireEvent(window,new Event('focus'));await screen.findByText('목록 오류');expect(screen.getByText('보존할 요청')).toBe(row);});

it('definite access failure clears stale privileged detail',async()=>{mocks.detail.mockResolvedValue(base);hub('/operations/requests?type=PAYMENT_CONFIRMATION_REQUEST&request=one');await screen.findByRole('heading',{name:'테스트 입금자'});mocks.detail.mockRejectedValueOnce(new PaymentFailure('권한 없음',true));fireEvent(window,new Event('focus'));await screen.findByText('권한 없음');expect(screen.queryByRole('heading',{name:'테스트 입금자'})).toBeNull();});

it('edit keeps version captured when opened across background refresh',async()=>{const r=repo();const ui=render(<PaymentDetail item={base} repository={r} onRefresh={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'수정'}));ui.rerender(<PaymentDetail item={{...base,version:3}} repository={r} onRefresh={async()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'수정 저장'}));await waitFor(()=>expect(r.command).toHaveBeenCalledWith(expect.objectContaining({action:'UPDATED',version:2})));});
