// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {RequestHubWorkspace} from './RequestHubWorkspace';
import {emptyPaymentAccess,type PaymentDetail} from './paymentRequestTypes';
import {PaymentFailure} from './paymentRequestRepository';
const api=vi.hoisted(()=>({list:vi.fn(),detail:vi.fn(),command:vi.fn()}));
vi.mock('./paymentRequestRepository',async original=>({...await original<typeof import('./paymentRequestRepository')>(),paymentRequestRepository:api}));
vi.mock('../lib/supabase',()=>({supabase:{rpc:vi.fn()}}));
let item:PaymentDetail;
const row=()=>({id:item.id,request_type:item.request_type,display_title:'예약금 확인',counterparty:'직원',status:item.status,lifecycle:item.status==='CONFIRMED'?'CLOSED':'OPEN',created_at:'2026-10-08T00:00:00Z',due_at:null});
function tree(path='/operations/requests',revision=0){return <MemoryRouter initialEntries={[path]}><RequestHubWorkspace userId="reviewer" taskAccess={{enabled:true,can_create:false,owner:false}} paymentAccess={{...emptyPaymentAccess,confirmation_enabled:true,view_all:true}} revision={revision}/></MemoryRouter>;}
beforeEach(()=>{item={id:'one',request_type:'PAYMENT_CONFIRMATION_REQUEST',payer_name:'홍길동',dog_name:'보리',reported_amount:100000,requester_name:'직원',handler_name:'대표',status:'REQUESTED',version:1,can_process:true,can_cancel:false};api.list.mockImplementation(async()=>({count:1,items:[row()]}));api.detail.mockImplementation(async()=>({...item}));api.command.mockImplementation(async p=>{item={...item,status:p.action,version:2};return {id:item.id,status:item.status,version:2};});});
afterEach(()=>{cleanup();vi.resetAllMocks();});
async function ready(){await screen.findByText('100,000원');await waitFor(()=>expect(screen.getByRole('button',{name:'입금 확인'})).toBeEnabled());}
it.each(['REQUESTED','NOT_FOUND'])('%s confirms inline with one command and no navigation',async status=>{item.status=status;render(tree());await ready();const article=screen.getByRole('article');fireEvent.click(screen.getByRole('button',{name:'입금 확인'}));expect(api.command).not.toHaveBeenCalled();const confirm=screen.getByRole('button',{name:'확인 처리'});fireEvent.click(confirm);fireEvent.click(confirm);await screen.findByText('입금 확인 완료');expect(screen.getByRole('article')).toBe(article);expect(screen.queryByRole('button',{name:'목록으로'})).toBeNull();expect(api.command).toHaveBeenCalledOnce();expect(api.command.mock.calls[0][0]).toMatchObject({id:'one',version:1,action:'CONFIRMED',payload:{note:null}});expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull();});
it('REQUESTED becomes NOT_FOUND then CONFIRMED using updated version',async()=>{render(tree());await ready();fireEvent.click(screen.getByRole('button',{name:'입금 미확인'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'입금 미확인'})).toBeNull());expect(screen.getByText('입금 미확인',{selector:'.payment-inline-status'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'입금 확인'}));fireEvent.click(screen.getByRole('button',{name:'확인 처리'}));await screen.findByText('입금 확인 완료');expect(api.command.mock.calls[1][0].version).toBe(2);});
it.each(['CONFIRMED','CANCELLED'])('%s has no processing action',async status=>{item.status=status;render(tree());await screen.findByText('100,000원');expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull();expect(screen.queryByRole('button',{name:'입금 미확인'})).toBeNull();expect(api.command).not.toHaveBeenCalled();});
it('server can_process false fails closed',async()=>{item.can_process=false;render(tree());await screen.findByText('100,000원');expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull();});
it('detail failure never exposes a processing action',async()=>{api.detail.mockRejectedValue(new Error('unavailable'));render(tree());await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull();});
it('definite command failure preserves status and allows retry with fresh attempt',async()=>{api.command.mockRejectedValueOnce(new PaymentFailure('권한 없음',true));render(tree());await ready();fireEvent.click(screen.getByRole('button',{name:'입금 미확인'}));await screen.findByText('권한 없음');expect(screen.getByText('확인 대기',{selector:'.payment-inline-status'})).toBeTruthy();expect(screen.getByRole('button',{name:'입금 미확인'})).toBeEnabled();});
it('uncertain command retains same request id and blocks snapshot refresh',async()=>{api.command.mockRejectedValueOnce(new Error('연결 오류'));render(tree());await ready();fireEvent.click(screen.getByRole('button',{name:'입금 미확인'}));await screen.findByText('연결 오류');expect(screen.getByRole('button',{name:'목록 갱신'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'같은 요청으로 결과 확인'}));await waitFor(()=>expect(api.command).toHaveBeenCalledTimes(2));expect(api.command.mock.calls[0][0]).toBe(api.command.mock.calls[1][0]);});
it('focus/revision refresh does not move a processed row; explicit refresh restores canonical pagination',async()=>{api.list.mockImplementation(async()=>({count:51,items:item.status==='CONFIRMED'?[{...row(),id:'next',display_title:'서버 다음 요청',status:'REQUESTED'}]:[row()]}));const ui=render(tree());await ready();const article=screen.getByRole('article');fireEvent.click(screen.getByRole('button',{name:'입금 확인'}));fireEvent.click(screen.getByRole('button',{name:'확인 처리'}));await screen.findByText('입금 확인 완료');fireEvent(window,new Event('focus'));fireEvent(document,new Event('visibilitychange'));ui.rerender(tree('/operations/requests',1));await act(async()=>{});expect(api.list).toHaveBeenCalledTimes(1);expect(screen.getByRole('article')).toBe(article);expect(screen.getByText('51건')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'목록 갱신'}));await screen.findByText('서버 다음 요청');expect(api.list).toHaveBeenCalledTimes(2);expect(screen.getByText('51건')).toBeTruthy();});
it('card body enters detail and back resumes fetching rather than remaining frozen',async()=>{render(tree());await ready();fireEvent.click(screen.getByRole('button',{name:'입금 미확인'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'입금 미확인'})).toBeNull());fireEvent.click(within(screen.getByRole('article')).getByRole('button',{name:/예약금 확인/}));await screen.findByRole('heading',{name:'홍길동'});fireEvent.click(screen.getByRole('button',{name:'목록으로'}));await screen.findByRole('article');expect(api.list).toHaveBeenCalledTimes(2);expect(screen.queryByText('조회 순서·건수 유지 중 · 최신 목록은 갱신해주세요.')).toBeNull();});
it.each(['sent','all'])('%s retains old row UI without inline commands or enrichment',async scope=>{render(tree('/operations/requests?scope='+scope));await screen.findByText('예약금 확인');expect(screen.queryByRole('article')).toBeNull();expect(api.detail).not.toHaveBeenCalled();});
it('Task-only inbox has no new inline controls or batch notice',async()=>{api.list.mockResolvedValue({items:[{...row(),request_type:'TASK_REQUEST'}],count:1});render(tree('/operations/requests?type=TASK_REQUEST'));await screen.findByText('예약금 확인');expect(screen.queryByRole('article')).toBeNull();expect(screen.queryByRole('button',{name:'목록 갱신'})).toBeNull();expect(api.detail).not.toHaveBeenCalled();});
it('two consecutive requests preserve order and use separate command identities',async()=>{api.list.mockResolvedValue({items:[row(),{...row(),id:'two',display_title:'두 번째 예약금'}],count:2});api.detail.mockImplementation(async(_type,id)=>({...item,id}));api.command.mockImplementation(async p=>({id:p.id,version:2,status:p.action}));render(tree());await waitFor(()=>expect(screen.getAllByRole('button',{name:'입금 확인'})).toHaveLength(2));const nodes=screen.getAllByRole('article');for(const node of nodes){fireEvent.click(within(node).getByRole('button',{name:'입금 확인'}));fireEvent.click(within(node).getByRole('button',{name:'확인 처리'}));await within(node).findByText('입금 확인 완료');}expect(screen.getAllByRole('article')).toEqual(nodes);expect(api.command.mock.calls.map(c=>c[0].id)).toEqual(['one','two']);expect(new Set(api.command.mock.calls.map(c=>c[0].key)).size).toBe(2);expect(api.list).toHaveBeenCalledOnce();});
it('pagination fetch still uses server offset, count and exact row order after inline handling',async()=>{api.list.mockImplementation(async(_scope,_type,_filter,offset)=>({items:offset?[{...row(),id:'page2',display_title:'서버 페이지 2'}]:[row()],count:51}));render(tree());await ready();fireEvent.click(screen.getByRole('button',{name:'입금 미확인'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'입금 미확인'})).toBeNull());fireEvent.click(screen.getByRole('button',{name:'다음'}));await screen.findByText('서버 페이지 2');expect(api.list).toHaveBeenLastCalledWith('inbox','ALL','all',50);expect(screen.getByText('51건')).toBeTruthy();});

it('compact card names the payer without inventing a guardian relationship',async()=>{render(tree());await ready();const card=screen.getByRole('article');expect(within(card).getByText('입금 확인 대상')).toBeTruthy();expect(within(card).getByText('홍길동')).toBeTruthy();expect(within(card).getByText('100,000원')).toBeTruthy();expect(within(card).getByText('반려견')).toBeTruthy();expect(within(card).getByText('보리')).toBeTruthy();expect(within(card).getByText('요청자')).toBeTruthy();expect(within(card).getByText('예약금 확인')).toBeTruthy();expect(within(card).queryByText('보호자')).toBeNull();expect(screen.queryByText('목록에서 연속 처리할 수 있습니다.')).toBeNull();});

it('administrative cancellation uses a separate presentation marker without changing status',async()=>{api.list.mockImplementation(async()=>({count:1,items:[{...row(),administrative_cancelled:true}]}));item.can_process=false;render(tree());await screen.findByText('100,000원');const card=screen.getByRole('article');expect(card).toHaveAttribute('data-status','REQUESTED');expect(card).toHaveAttribute('data-administrative-cancelled','true');expect(within(card).getByRole('status')).toHaveTextContent('관리 종료');expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull();expect(api.command).not.toHaveBeenCalled();});
