// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {PaymentReceivedHistory,movePaymentHistoryDate,paymentHistoryToday} from './PaymentReceivedHistory';
import {RequestHubWorkspace} from './RequestHubWorkspace';
import {emptyPaymentAccess,type HubRow} from './paymentRequestTypes';
const api=vi.hoisted(()=>({list:vi.fn(),history:vi.fn(),detail:vi.fn(),command:vi.fn()}));
vi.mock('./paymentRequestRepository',async original=>({...await original<typeof import('./paymentRequestRepository')>(),paymentRequestRepository:api}));
vi.mock('../lib/supabase',()=>({supabase:{rpc:vi.fn()}}));
const row=(id:string,status='REQUESTED'):HubRow=>({id,request_type:'PAYMENT_CONFIRMATION_REQUEST',status,lifecycle:['CONFIRMED','CANCELLED'].includes(status)?'CLOSED':'OPEN',display_title:id,counterparty:'직원',created_at:'2026-10-01T00:00:00Z',due_at:null});
beforeEach(()=>{sessionStorage.clear();api.list.mockImplementation(async(_scope,type,_filter,offset)=>type==='TASK_REQUEST'?{count:1,items:[{...row('완료 업무'),request_type:'TASK_REQUEST',status:'COMPLETED',lifecycle:'CLOSED'}]}:{count:70,items:Array.from({length:offset?20:50},(_,i)=>row('대기 '+(offset+i)))});api.history.mockImplementation(async(_type,_date,_offset,openOffset)=>({open:await api.list('inbox','PAYMENT_CONFIRMATION_REQUEST','active',openOffset),count:30,items:Array.from({length:30},(_,i)=>row('이력 '+i,'CONFIRMED'))}));api.detail.mockImplementation(async(_type,id)=>({id,request_type:'PAYMENT_CONFIRMATION_REQUEST',status:id.startsWith('이력')?'CONFIRMED':'REQUESTED',version:1,payer_name:id,reported_amount:1000,requester_name:'직원',handler_name:'대표',can_process:!id.startsWith('이력'),can_cancel:false}));api.command.mockResolvedValue({id:'대기 0',status:'CONFIRMED',version:2});});
afterEach(()=>{cleanup();vi.resetAllMocks();vi.useRealTimers();sessionStorage.clear();});
function view(path='/operations/requests?paymentView=history&historyDate=2026-10-08'){return render(<MemoryRouter initialEntries={[path]}><PaymentReceivedHistory userId="actor" type="PAYMENT_CONFIRMATION_REQUEST" filter="all" revision={0} onOpen={vi.fn()}/></MemoryRouter>);}
it('70 OPEN and 30 CLOSED have independent server counts and pages',async()=>{view();await screen.findByText('처리 대기 70건');expect(screen.getByText('처리 이력 30건')).toBeInTheDocument();const open=screen.getByRole('region',{name:'처리 대기'}),closed=screen.getByRole('region',{name:'처리 이력'});expect(within(open).getAllByRole('article')).toHaveLength(50);expect(within(closed).getAllByRole('article')).toHaveLength(30);fireEvent.click(within(open).getByRole('button',{name:'다음'}));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith('inbox','PAYMENT_CONFIRMATION_REQUEST','active',50));expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-08',0,50);await waitFor(()=>expect(within(open).getAllByRole('article')).toHaveLength(20));});
it('history date navigation never restricts OPEN queue',async()=>{view();await screen.findByText('처리 대기 70건');fireEvent.click(screen.getByRole('button',{name:'다음 날짜'}));await waitFor(()=>expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-09',0,0));expect(api.list).toHaveBeenLastCalledWith('inbox','PAYMENT_CONFIRMATION_REQUEST','active',0);});
it('KST today uses Seoul across UTC midnight and date steps',()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-07T15:01:00Z'));expect(paymentHistoryToday()).toBe('2026-10-08');vi.setSystemTime(new Date('2026-10-07T14:59:00Z'));expect(paymentHistoryToday()).toBe('2026-10-07');expect(movePaymentHistoryDate('2026-10-01',-1)).toBe('2026-09-30');});
it('successful inline command preserves position until explicit refresh moves row',async()=>{api.list.mockResolvedValue({count:1,items:[row('対象')]});api.history.mockImplementation(async()=>({open:await api.list('inbox','PAYMENT_CONFIRMATION_REQUEST','active',0),count:0,items:[]}));view();fireEvent.click(await screen.findByRole('button',{name:'입금 확인'}));fireEvent.click(screen.getByRole('button',{name:'확인 처리'}));await screen.findByText('입금 확인 완료');expect(screen.getByText('처리 대기 1건')).toBeInTheDocument();const calls=api.list.mock.calls.length;await act(async()=>fireEvent(window,new Event('focus')));expect(api.list).toHaveBeenCalledTimes(calls);api.list.mockResolvedValue({count:0,items:[]});api.history.mockImplementation(async()=>({open:await api.list('inbox','PAYMENT_CONFIRMATION_REQUEST','active',0),count:1,items:[row('対象','CONFIRMED')]}));fireEvent.click(screen.getByRole('button',{name:'결제 목록 갱신'}));await screen.findByText('처리 이력 1건');expect(screen.getAllByRole('article')).toHaveLength(1);expect(screen.getByText('처리 대기 0건')).toBeInTheDocument();});
it('empty date has clear state and failed refresh retains existing rows',async()=>{api.history.mockImplementation(async()=>({open:await api.list('inbox','PAYMENT_CONFIRMATION_REQUEST','active',0),count:0,items:[]}));view();await screen.findByText('선택한 날짜에 처리된 요청이 없습니다.');api.history.mockRejectedValue(new Error('조회 실패'));fireEvent.click(screen.getByRole('button',{name:'결제 목록 갱신'}));await screen.findByRole('alert');expect(screen.getAllByText('대기 0').length).toBeGreaterThan(0);});
it('ALL initial includes closed Task history and separate payment sections exactly once',async()=>{render(<MemoryRouter><RequestHubWorkspace userId="actor" taskAccess={{enabled:true,can_create:false,owner:false}} paymentAccess={{...emptyPaymentAccess,confirmation_enabled:true}} revision={0}/></MemoryRouter>);await screen.findByText('완료 업무');await screen.findByText('처리 대기 70건');expect(api.list).toHaveBeenCalledWith('inbox','TASK_REQUEST','all',0);expect(screen.getAllByRole('article').filter(node=>node.getAttribute('aria-label')==='대기 0')).toHaveLength(1);expect(screen.queryByText('지급 요청')).toBeNull();});
it('explicit legacy filter does not silently replace mixed-list contract',async()=>{render(<MemoryRouter initialEntries={['/operations/requests?filter=done']}><RequestHubWorkspace userId="actor" taskAccess={{enabled:true,can_create:false,owner:false}} paymentAccess={{...emptyPaymentAccess,confirmation_enabled:true}} revision={0}/></MemoryRouter>);await waitFor(()=>expect(api.list).toHaveBeenCalledWith('inbox','ALL','done',0));expect(api.history).not.toHaveBeenCalled();});
it('explicit filters persist in date view without falling back to mixed list',async()=>{render(<MemoryRouter><RequestHubWorkspace userId="actor" taskAccess={{enabled:true,can_create:false,owner:false}} paymentAccess={{...emptyPaymentAccess,confirmation_enabled:true}} revision={0}/></MemoryRouter>);await screen.findByText('처리 대기 70건');fireEvent.change(screen.getByLabelText('상태'),{target:{value:'done'}});expect(screen.queryByRole('region',{name:'처리 대기'})).toBeNull();expect(screen.getByRole('region',{name:'처리 이력'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('상태'),{target:{value:'active'}});expect(screen.getByRole('region',{name:'처리 대기'})).toBeInTheDocument();expect(screen.queryByRole('region',{name:'처리 이력'})).toBeNull();});
it('CLOSED pagination is independent of OPEN offset',async()=>{api.history.mockImplementation(async(_type,_date,offset,openOffset)=>({open:await api.list('inbox','PAYMENT_CONFIRMATION_REQUEST','active',openOffset),count:65,items:Array.from({length:offset?15:50},(_,i)=>row('이력 '+(offset+i),'CONFIRMED'))}));view();await screen.findByText('처리 이력 65건');fireEvent.click(within(screen.getByRole('navigation',{name:'처리 이력 페이지'})).getByRole('button',{name:'다음'}));await waitFor(()=>expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-08',50,0));expect(api.list).toHaveBeenLastCalledWith('inbox','PAYMENT_CONFIRMATION_REQUEST','active',0);});
it('storage failure sends no command and does not freeze background refresh',async()=>{api.list.mockResolvedValue({count:1,items:[row('대기 0')]});api.history.mockImplementation(async()=>({open:await api.list(),count:0,items:[]}));const save=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('blocked');});view();fireEvent.click(await screen.findByRole('button',{name:'입금 미확인'}));await screen.findByRole('alert');expect(api.command).not.toHaveBeenCalled();const calls=api.history.mock.calls.length;fireEvent(window,new Event('focus'));await waitFor(()=>expect(api.history.mock.calls.length).toBeGreaterThan(calls));save.mockRestore();});
it('revoked access fails closed instead of retaining actionable cards',async()=>{const {PaymentFailure}=await import('./paymentRequestRepository');api.list.mockResolvedValue({count:1,items:[row('대기 0')]});api.history.mockImplementation(async()=>({open:await api.list(),count:0,items:[]}));view();await screen.findByText('처리 대기 1건');api.history.mockRejectedValue(new PaymentFailure('권한 없음',true));fireEvent.click(screen.getByRole('button',{name:'결제 목록 갱신'}));await screen.findByText('권한 없음');expect(screen.queryByRole('article')).toBeNull();});
it('invalid URL date fails to safe KST today rather than sending an invalid range',async()=>{view('/operations/requests?historyDate=2026-99-99&paymentView=history');await waitFor(()=>expect(api.history).toHaveBeenCalledWith('PAYMENT_CONFIRMATION_REQUEST',paymentHistoryToday(),0,0));});
it('date-page fetch keeps the unrelated OPEN rows mounted',async()=>{view();await screen.findByText('처리 대기 70건');const card=screen.getAllByRole('article').find(e=>e.getAttribute('aria-label')==='대기 0');api.history.mockImplementationOnce(()=>new Promise(()=>{}));fireEvent.click(screen.getByRole('button',{name:'다음 날짜'}));expect(screen.getAllByRole('article').find(e=>e.getAttribute('aria-label')==='대기 0')).toBe(card);expect(screen.getByText('처리 대기 70건')).toBeInTheDocument();});
it.each(['OPEN','CLOSED'])('%s 51 → 50 corrects only the invalid offset without a false empty state',async area=>{
 const openArea=area==='OPEN';let count=51;let finish:((value:unknown)=>void)|undefined;
 const result=(closedOffset:number,openOffset:number)=>({open:{count:openArea?count:70,items:Array.from({length:Math.max(0,Math.min(50,(openArea?count:70)-openOffset))},(_,i)=>row('대기 '+(openOffset+i)))},count:openArea?70:count,items:Array.from({length:Math.max(0,Math.min(50,(openArea?70:count)-closedOffset))},(_,i)=>row('이력 '+(closedOffset+i),'CONFIRMED'))});
 api.history.mockImplementation(async(_type,_date,closedOffset,openOffset)=>result(closedOffset,openOffset));
 view('/operations/requests?paymentView=history&historyDate=2026-10-08&paymentOpenOffset=50&paymentClosedOffset=50&filter=all');
 await screen.findByText(openArea?'처리 대기 51건':'처리 이력 51건');
 const unaffected=screen.getByRole('region',{name:openArea?'처리 이력':'처리 대기'});const card=within(unaffected).getAllByRole('article')[0];
 count=50;
 api.history.mockImplementationOnce(async()=>result(50,50)).mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));
 fireEvent.click(screen.getByRole('button',{name:'결제 목록 갱신'}));
 await waitFor(()=>expect(api.history).toHaveBeenCalledTimes(3));
 expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-08',openArea?50:0,openArea?0:50);
 expect(screen.queryByText('처리 대기 요청이 없습니다.')).toBeNull();expect(screen.queryByText('선택한 날짜에 처리된 요청이 없습니다.')).toBeNull();
 expect(within(unaffected).getAllByRole('article')[0]).toBe(card);
 await act(async()=>finish?.(result(openArea?50:0,openArea?0:50)));
 await screen.findByText(openArea?'처리 대기 50건':'처리 이력 50건');
 expect(api.history).toHaveBeenCalledTimes(3);
 expect(within(screen.getByRole('region',{name:openArea?'처리 대기':'처리 이력'})).getAllByRole('article')).toHaveLength(50);
});
it.each(['OPEN','CLOSED'])('%s zero count corrects to offset zero once and shows a genuine empty state',async area=>{
 const openArea=area==='OPEN';api.history.mockResolvedValue({open:{count:openArea?0:70,items:openArea?[]:[row('대기 50')]},count:openArea?70:0,items:openArea?[row('이력 50','CONFIRMED')]:[]});
 view('/operations/requests?paymentView=history&historyDate=2026-10-08&paymentOpenOffset=50&paymentClosedOffset=50');
 await screen.findByText(openArea?'처리 대기 요청이 없습니다.':'선택한 날짜에 처리된 요청이 없습니다.');
 expect(api.history).toHaveBeenCalledTimes(2);expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-08',openArea?50:0,openArea?0:50);
});
it('both invalid offsets are corrected in a single navigation and follow-up request',async()=>{
 api.history.mockResolvedValue({open:{count:0,items:[]},count:0,items:[]});view('/operations/requests?paymentView=history&historyDate=2026-10-08&paymentOpenOffset=100&paymentClosedOffset=50');
 await screen.findByText('처리 대기 0건');expect(api.history).toHaveBeenCalledTimes(2);expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-08',0,0);
});
it('inline snapshot holds an out-of-range page until explicit refresh',async()=>{
 let count=51;api.history.mockImplementation(async(_type,_date,_closed,open)=>({open:{count,items:open<count?[row('대기 50')]:[]},count:0,items:[]}));
 view('/operations/requests?paymentView=history&historyDate=2026-10-08&paymentOpenOffset=50');
 fireEvent.click(await screen.findByRole('button',{name:'입금 확인'}));fireEvent.click(screen.getByRole('button',{name:'확인 처리'}));await screen.findByText('입금 확인 완료');count=50;
 await act(async()=>{fireEvent(window,new Event('focus'));fireEvent(document,new Event('visibilitychange'));});expect(api.history).toHaveBeenCalledTimes(1);expect(screen.getByText('처리 대기 51건')).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'결제 목록 갱신'}));await screen.findByText('처리 대기 50건');expect(api.history).toHaveBeenCalledTimes(3);expect(api.history).toHaveBeenLastCalledWith('PAYMENT_CONFIRMATION_REQUEST','2026-10-08',0,0);
});
