// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {PaymentComposer} from './PaymentComposer';
import {PaymentDetail} from './PaymentDetail';
import {paymentRequestRepository,PaymentFailure,type PaymentRepository} from './paymentRequestRepository';
import {availableRequestTypes,paymentAmount,paymentDue,paymentRequestPath} from './paymentRequestPresentation';
import {emptyPaymentAccess,type PaymentDetail as Detail} from './paymentRequestTypes';
import {PaymentCapabilityManagement} from './PaymentCapabilityManagement';
const mock=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('../lib/supabase',()=>({supabase:{rpc:mock.rpc}}));
afterEach(()=>{cleanup();vi.restoreAllMocks();});
const people=[{id:'handler',name:'검수 담당자'},{id:'other',name:'두 번째 담당자'}];
function repository(rows=people.slice(0,1)){return {...paymentRequestRepository,handlers:vi.fn().mockResolvedValue(rows),command:vi.fn().mockResolvedValue({id:'result',version:1,status:'REQUESTED'})} satisfies PaymentRepository;}
function fillConfirmation(){fireEvent.change(screen.getByLabelText('입금자명 / 확인 대상 이름'),{target:{value:'신규 입금자'}});fireEvent.change(screen.getByLabelText('확인 금액'),{target:{value:'100000'}});}
it('new payer without existing references, one handler auto-selected and exact payload',async()=>{const repo=repository();render(<PaymentComposer type="PAYMENT_CONFIRMATION_REQUEST" userId="create-test" repository={repo} onCreated={()=>{}}/>);await screen.findByText('검수 담당자');fillConfirmation();fireEvent.click(screen.getByText('결제 확인 요청 보내기'));await waitFor(()=>expect(repo.command).toHaveBeenCalledTimes(1));expect(repo.command.mock.calls[0][0]).toMatchObject({version:0,type:'PAYMENT_CONFIRMATION_REQUEST',payload:{handler_id:'handler',payer_name:'신규 입금자',amount:100000,dog_name:null,note:null}});expect(JSON.stringify(repo.command.mock.calls)).not.toMatch(/sale_id|customer_id|dog_id/);});
it('zero handler disables create',async()=>{const repo=repository([]);render(<PaymentComposer type="PAYMENT_REQUEST" userId="zero" repository={repo} onCreated={()=>{}}/>);expect(screen.getByText('지급 요청 보내기')).toHaveProperty('disabled',true);expect(repo.command).not.toHaveBeenCalled();});
it('multiple handlers require explicit single selection',async()=>{const repo=repository(people);render(<PaymentComposer type="PAYMENT_CONFIRMATION_REQUEST" userId="multiple" repository={repo} onCreated={()=>{}}/>);await screen.findByText('두 번째 담당자');fillConfirmation();fireEvent.click(screen.getByText('결제 확인 요청 보내기'));expect(repo.command).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('확인 담당자'),{target:{value:'other'}});fireEvent.click(screen.getByText('결제 확인 요청 보내기'));await waitFor(()=>expect(repo.command).toHaveBeenCalledTimes(1));expect(repo.command.mock.calls[0][0].payload.handler_id).toBe('other');});
it.each(['0','-1','1.2','1e3','2147483648',''])('invalid KRW %s',v=>expect(()=>paymentAmount(v)).toThrow());
it('optional due has no fabricated midnight and KST future roundtrip',()=>{expect(paymentDue('')).toBeNull();expect(paymentDue('2099-10-07T00:30')).toBe('2099-10-06T15:30:00.000Z');expect(()=>paymentDue('2000-01-01T12:00')).toThrow();expect(()=>paymentDue('2099-10-07')).toThrow();});
it('payment fresh due empty and past date blocks RPC',async()=>{const repo=repository();render(<PaymentComposer type="PAYMENT_REQUEST" userId="due" repository={repo} onCreated={()=>{}}/>);await screen.findByText('검수 담당자');const due=screen.getByLabelText('완료 희망일시');expect(due).toHaveProperty('value','');expect(due.getAttribute('type')).toBe('text');fireEvent.change(screen.getByLabelText('제목'),{target:{value:'사료'}});fireEvent.change(screen.getByLabelText('지급 대상'),{target:{value:'업체'}});fireEvent.change(screen.getByLabelText('금액'),{target:{value:'420000'}});fireEvent.change(screen.getByLabelText('사유'),{target:{value:'테스트'}});fireEvent.focus(due);fireEvent.change(due,{target:{value:'2000-01-01T12:00'}});fireEvent.submit(screen.getByText('지급 요청 보내기').closest('form')!);expect(repo.command).not.toHaveBeenCalled();expect(screen.getByRole('alert').textContent).toContain('현재보다 이후');});
it('uncertain create keeps exact request key and payload for retry',async()=>{const repo=repository();repo.command.mockRejectedValueOnce(new PaymentFailure('unknown',false));render(<PaymentComposer type="PAYMENT_CONFIRMATION_REQUEST" userId="retry" repository={repo} onCreated={()=>{}}/>);await screen.findByText('검수 담당자');fillConfirmation();fireEvent.click(screen.getByText('결제 확인 요청 보내기'));await screen.findByText('unknown');fireEvent.click(screen.getByText('같은 요청으로 결과 확인'));await waitFor(()=>expect(repo.command).toHaveBeenCalledTimes(2));expect(repo.command.mock.calls[0][0]).toEqual(repo.command.mock.calls[1][0]);});
const base:Detail={id:'one',request_type:'PAYMENT_REQUEST',requester_name:'요청자',handler_name:'담당자',title:'지급',requested_amount:420000,status:'REQUESTED',version:1,can_cancel:false,can_process:true};
it('read-only render does not ACK, ACK before complete, same version',async()=>{const repo=repository();const ui=render(<PaymentDetail item={base} repository={repo} onRefresh={async()=>{}}/>);expect(repo.command).not.toHaveBeenCalled();expect(screen.queryByText('지급 완료',{selector:'button'})).toBeNull();fireEvent.click(screen.getByText('확인했습니다'));await waitFor(()=>expect(repo.command).toHaveBeenCalledTimes(1));expect(repo.command.mock.calls[0][0]).toMatchObject({action:'ACKNOWLEDGED',version:1});ui.rerender(<PaymentDetail item={{...base,status:'ACKNOWLEDGED',version:2}} repository={repo} onRefresh={async()=>{}}/>);expect(screen.getByText('지급 완료',{selector:'button'})).toBeTruthy();expect(screen.queryByText('요청 취소')).toBeNull();});
it('confirmation optional result note and terminal action absence',async()=>{const repo=repository();const ui=render(<PaymentDetail item={{...base,request_type:'PAYMENT_CONFIRMATION_REQUEST'}} repository={repo} onRefresh={async()=>{}}/>);fireEvent.click(screen.getByText('입금 미확인',{selector:'button'}));await waitFor(()=>expect(repo.command).toHaveBeenCalledTimes(1));expect(repo.command.mock.calls[0][0].payload).toEqual({note:null});ui.rerender(<PaymentDetail item={{...base,request_type:'PAYMENT_CONFIRMATION_REQUEST',status:'CONFIRMED'}} repository={repo} onRefresh={async()=>{}}/>);expect(screen.queryByText('입금 확인',{selector:'button'})).toBeNull();});
it('reject requires reason',()=>{const repo=repository();render(<PaymentDetail item={base} repository={repo} onRefresh={async()=>{}}/>);fireEvent.click(screen.getByText('반려'));expect(repo.command).not.toHaveBeenCalled();});
it('launcher filters source and capability independently; owner has no implied create',()=>{const task={enabled:true,can_create:false,owner:true};expect(availableRequestTypes(task,emptyPaymentAccess)).toEqual([]);expect(availableRequestTypes(task,{...emptyPaymentAccess,confirmation_create:true})).toEqual([]);expect(availableRequestTypes(task,{...emptyPaymentAccess,confirmation_enabled:true,confirmation_create:true})).toEqual(['PAYMENT_CONFIRMATION_REQUEST']);expect(availableRequestTypes({...task,can_create:true},{...emptyPaymentAccess,confirmation_enabled:true,confirmation_create:true,payment_enabled:true,payment_create:true})).toHaveLength(3);});
it('deep link stays canonical SPA route',()=>expect(paymentRequestPath('PAYMENT_REQUEST','one')).toBe('/operations/requests?type=PAYMENT_REQUEST&request=one'));
describe('server-scoped permission panel',()=>{
 it.each([['owner',['PAYMENT_REQUEST_CREATE']],['finance',['PAYMENT_REQUEST_PROCESS','PAYMENT_REQUESTS_VIEW_ALL']],['combined',['PAYMENT_REQUEST_CREATE','PAYMENT_REQUEST_PROCESS']]])('%s renders only server-authorized capability sections',async(_role,caps)=>{mock.rpc.mockResolvedValue({data:[{id:'target',name:'검수',active:true,operation_active:true,capabilities:Object.fromEntries((caps as string[]).map(c=>[c,{active:false,version:0}]))}],error:null});render(<PaymentCapabilityManagement selectedId="target"/>);await waitFor(()=>expect(screen.getAllByRole('switch')).toHaveLength(caps.length));});
});
