import {useCallback,useEffect,useRef,useState} from 'react';
import type {CapabilityRow} from '../taskRequests/taskRequestRepository';
import {paymentRequestRepository,PaymentFailure} from './paymentRequestRepository';
const labels:Record<string,string>={PAYMENT_CONFIRMATION_REQUEST_CREATE:'결제 확인 요청',PAYMENT_REQUEST_CREATE:'지급 요청',PAYMENT_CONFIRMATION_REVIEW:'결제 확인 처리',PAYMENT_REQUEST_PROCESS:'지급 요청 처리',PAYMENT_REQUESTS_VIEW_ALL:'금융 요청 전체 조회'};
export function PaymentCapabilityManagement({selectedId}:{selectedId:string}){
 const [row,setRow]=useState<CapabilityRow>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(false);const pending=useRef<{cap:string;active:boolean;version:number;key:string}|undefined>(undefined),lock=useRef(false);
 const load=useCallback(async()=>{try{setRow((await paymentRequestRepository.directory()).find(r=>r.id===selectedId));}catch(e){setError((e as Error).message);}},[selectedId]);useEffect(()=>{void load();},[load]);
 const set=(cap:string,active:boolean)=>{if(lock.current)return;const p=pending.current||{cap,active,version:row?.capabilities[cap]?.version||0,key:crypto.randomUUID()};pending.current=p;lock.current=true;setBusy(true);setRetry(true);void paymentRequestRepository.setCapability(selectedId,p.cap,p.active,p.version,p.key).then(async()=>{pending.current=undefined;setRetry(false);setError('');await load();}).catch(e=>{if(e instanceof PaymentFailure&&e.definite){pending.current=undefined;setRetry(false);}setError(e.message);}).finally(()=>{lock.current=false;setBusy(false);});};
 if(!row&&!error)return null;
 return <section className="staff-section">{error&&<p role="alert">{error}</p>}{row&&[true,false].map(create=>{const caps=Object.keys(row.capabilities).filter(k=>k.endsWith('_CREATE')===create);return caps.length>0&&<fieldset className="staff-capabilities" key={String(create)} disabled={busy||retry}><legend>{create?'요청 작성 권한':'금융 요청 처리 권한'}</legend>{caps.map(k=><label className="staff-capability" key={k}>{labels[k]}<input className="staff-switch" role="switch" type="checkbox" checked={row.capabilities[k].active} disabled={!row.active||(!row.operation_active&&!row.capabilities[k].active)} onChange={e=>set(k,e.target.checked)}/></label>)}</fieldset>;})}<p>실제 요청 작성·처리에는 활성 Operations 멤버십이 필요합니다.</p>{retry&&pending.current&&<button disabled={busy} onClick={()=>set(pending.current!.cap,pending.current!.active)}>같은 요청으로 결과 확인</button>}</section>;
}
