// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {RequestHubWorkspace} from './RequestHubWorkspace';
import {emptyPaymentAccess} from './paymentRequestTypes';
const api=vi.hoisted(()=>({list:vi.fn(),detail:vi.fn(),command:vi.fn(),taskDetail:vi.fn()}));
vi.mock('./paymentRequestRepository',async original=>({...await original<typeof import('./paymentRequestRepository')>(),paymentRequestRepository:api}));
vi.mock('../taskRequests/taskRequestRepository',async original=>({...await original<typeof import('../taskRequests/taskRequestRepository')>(),taskRequestRepository:{detail:api.taskDetail}}));
vi.mock('../lib/supabase',()=>({supabase:{rpc:vi.fn()}}));
const access={...emptyPaymentAccess,confirmation_enabled:true,payment_enabled:true,view_all:true};
const task={enabled:true,can_create:false,owner:false};
let status='NOT_FOUND';
const row=()=>({id:'pilot',request_type:'PAYMENT_CONFIRMATION_REQUEST',display_title:'확인 대상',counterparty:'요청자',status,lifecycle:status==='CONFIRMED'?'CLOSED':'OPEN',created_at:'2026-10-07T00:00:00Z',due_at:null});
const detail=()=>({id:'pilot',request_type:'PAYMENT_CONFIRMATION_REQUEST',payer_name:'확인 대상',reported_amount:100000,status,version:2,can_process:true,can_cancel:false,requester_name:'요청자',handler_name:'담당자'});
beforeEach(()=>{status='NOT_FOUND';api.list.mockImplementation(async(_s,_t,f)=>({items:f==='active'&&status==='CONFIRMED'||f==='done'&&status!=='CONFIRMED'?[]:[row()],count:f==='active'&&status==='CONFIRMED'||f==='done'&&status!=='CONFIRMED'?0:1}));api.detail.mockImplementation(async()=>detail());api.command.mockImplementation(async()=>{status='CONFIRMED';return {id:'pilot',version:3,status};});});
afterEach(()=>{cleanup();vi.resetAllMocks();});
function tree(path:string,revision=0,confirmation=true){return <MemoryRouter initialEntries={[path+(path.includes('?')?'&':'?')+'paymentView=list']}><RequestHubWorkspace userId="self" taskAccess={task} paymentAccess={{...access,confirmation_enabled:confirmation}} revision={revision}/></MemoryRouter>;}
it.each([['','all'],['?type=PAYMENT_CONFIRMATION_REQUEST','all'],['?type=TASK_REQUEST','active'],['?type=PAYMENT_REQUEST','active'],['?scope=sent','active'],['?scope=all','active'],['?filter=active','active'],['?filter=done','done'],['?filter=all','all']])('default/explicit contract %s',async(query,filter)=>{render(tree('/operations/requests'+query));await waitFor(()=>expect(api.list).toHaveBeenCalled());expect(api.list.mock.calls[0][2]).toBe(filter);expect(screen.getByLabelText('상태')).toHaveProperty('value',filter);});
it('confirmation OFF preserves existing default and hides confirmation type',async()=>{render(tree('/operations/requests',0,false));await waitFor(()=>expect(api.list).toHaveBeenCalledWith('inbox','ALL','active',0));expect(screen.queryByRole('option',{name:'결제 확인 요청'})).toBeNull();});
it.each(['REQUESTED','NOT_FOUND'])('%s confirmation keeps detail then history row on back',async(initial)=>{status=initial;render(tree('/operations/requests'));fireEvent.click(await screen.findByRole('button',{name:/확인 대상/}));const heading=await screen.findByRole('heading',{name:'확인 대상'});fireEvent.click(screen.getByRole('button',{name:'입금 확인'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull());expect(screen.getByRole('heading',{name:'확인 대상'})).toBe(heading);expect(screen.getByText('입금 확인')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'목록으로'}));await screen.findByRole('button',{name:/요청자 · 입금 확인/});expect(api.list).toHaveBeenLastCalledWith('inbox','ALL','all',0);expect(api.command).toHaveBeenCalledOnce();});
it('explicit filters survive tabs and detail back; closed hidden only for active',async()=>{status='CONFIRMED';render(tree('/operations/requests?filter=done'));fireEvent.click(await screen.findByRole('button',{name:/확인 대상/}));await screen.findByRole('heading',{name:'확인 대상'});fireEvent.click(screen.getByRole('button',{name:'목록으로'}));await screen.findByRole('button',{name:/확인 대상/});fireEvent.click(screen.getByRole('button',{name:'보낸 요청'}));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith('sent','ALL','done',0));fireEvent.click(screen.getByRole('button',{name:'받은 요청'}));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith('inbox','ALL','done',0));fireEvent.change(screen.getByLabelText('상태'),{target:{value:'active'}});await screen.findByText('요청이 없습니다.');expect(screen.queryByRole('button',{name:/확인 대상/})).toBeNull();fireEvent.change(screen.getByLabelText('상태'),{target:{value:'all'}});await screen.findByRole('button',{name:/확인 대상/});});
it('implicit sent/all defaults remain active; returning inbox restores all',async()=>{render(tree('/operations/requests'));await screen.findByText('확인 대상');for(const [label,scope]of [['보낸 요청','sent'],['전체 현황','all'],['받은 요청','inbox']]){fireEvent.click(screen.getByRole('button',{name:label}));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith(scope,'ALL',scope==='inbox'?'all':'active',0));}});
it('preserves canonical server order and count across refresh and revision',async()=>{const items=[{...row(),id:'task',display_title:'서버 기한 우선',due_at:'2026-10-09T00:00:00Z'},row(),{...row(),id:'closed',status:'CONFIRMED',lifecycle:'CLOSED',display_title:'완료 이력'}];api.list.mockResolvedValue({items,count:70});const ui=render(tree('/operations/requests'));await screen.findByText('완료 이력');expect(screen.getByText('70건')).toBeTruthy();expect([...document.querySelectorAll('.pt-task-row strong')].map(x=>x.textContent)).toEqual(items.map(x=>x.display_title));const node=screen.getByText('완료 이력');for(const event of ['focus','visibilitychange']){let resolve!:(v:unknown)=>void;api.list.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));fireEvent(event==='focus'?window:document,new Event(event));expect(screen.getByText('완료 이력')).toBe(node);await act(async()=>resolve({items,count:70}));}ui.rerender(tree('/operations/requests',1));await waitFor(()=>expect(api.list).toHaveBeenCalledTimes(4));expect(screen.getByText('완료 이력')).toBe(node);});

it.each([['','active'],['&filter=active','active'],['&filter=done','done'],['&filter=all','all']])('Task direct link back preserves implicit/explicit filter %s',async(query,filter)=>{api.taskDetail.mockResolvedValue({id:'task-one',title:'직접 진입 업무',body:'확인',due_at:'2099-10-08T09:00:00Z',requester_name:'요청자',targets:[],cancelled_at:null});render(tree('/operations/requests?task=task-one'+query));await screen.findByRole('heading',{name:'직접 진입 업무'});fireEvent.click(screen.getByRole('button',{name:'목록으로'}));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith('inbox','ALL',filter,0));expect(screen.getByLabelText('상태')).toHaveProperty('value',filter);});
it('51-row server pagination may move confirmed request to next page without changing count/order',async()=>{const others=Array.from({length:50},(_,i)=>({...row(),id:'other-'+i,display_title:'대기 업무 '+i,status:'REQUESTED',lifecycle:'OPEN'}));api.list.mockImplementation(async(_scope,_type,filter,offset)=>{expect(filter).toBe('all');const canonical=status==='CONFIRMED'?[...others,row()]:[row(),...others];return {count:51,items:canonical.slice(offset,offset+50)};});render(tree('/operations/requests'));fireEvent.click(await screen.findByRole('button',{name:/확인 대상/}));await screen.findByRole('heading',{name:'확인 대상'});fireEvent.click(screen.getByRole('button',{name:'입금 확인'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'입금 확인'})).toBeNull());fireEvent.click(screen.getByRole('button',{name:'목록으로'}));await screen.findByText('대기 업무 49');expect(screen.queryByRole('button',{name:/확인 대상/})).toBeNull();expect(screen.getByText('51건')).toBeTruthy();expect(api.list).toHaveBeenLastCalledWith('inbox','ALL','all',0);fireEvent.click(screen.getByRole('button',{name:'다음'}));await screen.findByRole('button',{name:/요청자 · 입금 확인/});expect(api.list).toHaveBeenLastCalledWith('inbox','ALL','all',50);expect(screen.getByText('51건')).toBeTruthy();});
