import {PaymentCapabilityManagement} from '../paymentRequests/PaymentCapabilityManagement';
import { RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { taskRequestRepository, TaskFailure, type TaskRepository, type CapabilityRow } from './taskRequestRepository';
import { StaffDirectory } from '../pages/StaffDirectory';
const labels: Record<string, string> = { ANNOUNCEMENT_PUBLISH: '공지 발행', ANNOUNCEMENT_RECEIPTS_VIEW: '공지 확인현황 조회', TASK_REQUEST_CREATE: '업무요청 발행' };
const help: Record<string, string> = { ANNOUNCEMENT_PUBLISH: '공지를 작성하고 직원에게 발행합니다.', ANNOUNCEMENT_RECEIPTS_VIEW: '수신자의 공지 확인 상태를 조회합니다.', TASK_REQUEST_CREATE: '직원에게 업무요청을 보낼 수 있습니다.' };
type Attempt = { id: string; capability: string; active: boolean; version: number; key: string };
export function CapabilityManagement({ repository = taskRequestRepository, selectedId }: { repository?: TaskRepository; selectedId?: string }) {
 const [rows, setRows] = useState<CapabilityRow[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false), [pending, setPending] = useState<Attempt | null>(null), [loading, setLoading] = useState(true), [saved, setSaved] = useState(''), [query, setQuery] = useState('');
 const lock = useRef(false);
 const load = useCallback(async () => { try { setRows(await repository.directory()); setError(''); return true; } catch (e) { setError((e as Error).message); setRows([]); return false; } finally { setLoading(false); } }, [repository]);
 useEffect(() => { void load(); }, [load]);
 const submit = (p: Attempt) => { if (lock.current) return; lock.current = true; setBusy(true); setPending(p); setError(''); setSaved(''); void repository.setCapability(p.id, p.capability, p.active, p.version, p.key).then(async () => { setPending(null); if (await load()) setSaved(p.id); }).catch(e => { if (e instanceof TaskFailure && e.definite) setPending(null); setError(e.message); }).finally(() => { lock.current = false; setBusy(false); }); };
 const detail = (id: string) => { const r = rows.find(row => row.id === id); return <section className="staff-section staff-cap-section"><header className="staff-section-header"><h3>업무 기능 권한</h3><button type="button" className="staff-cap-reload" aria-label="업무 기능 권한 새로고침" title="업무 기능 권한 새로고침" disabled={busy || !!pending} onClick={() => void load()}><RefreshCw size={16} aria-hidden="true" /></button></header>{loading && <p role="status">권한을 불러오는 중…</p>}{error && <p role="alert" className="staff-cap-error">{error}</p>}{pending && !busy && <button className="staff-cap-refresh" onClick={() => submit(pending)}>같은 요청으로 결과 확인</button>}{r && <><fieldset className="staff-capabilities" disabled={busy || !!pending || !r.active}><legend className="sr-only">업무 기능 권한 설정</legend>{Object.entries(labels).map(([key, label]) => <div className="staff-capability" key={key}><label htmlFor={`cap-${id}-${key}`}>{label}<small>{help[key]}</small></label><input className="staff-switch" role="switch" aria-label={label} id={`cap-${id}-${key}`} type="checkbox" checked={r.capabilities[key]?.active || false} disabled={key === 'TASK_REQUEST_CREATE' && !r.operation_active} onChange={e => submit({ id: r.id, capability: key, active: e.target.checked, version: r.capabilities[key]?.version || 0, key: crypto.randomUUID() })} /></div>)}</fieldset>{!r.active && <p>비활성 계정의 권한은 변경할 수 없습니다.</p>}{r.active && !r.operation_active && <p>업무요청 발행에는 활성 Operations 멤버십이 필요합니다.</p>}</>}<p className="staff-cap-status" role="status">{busy ? '권한을 저장하는 중…' : saved === id ? '저장되었습니다.' : '변경하면 바로 저장됩니다.'}</p></section>; };
 if (selectedId) return detail(selectedId);
 if (loading) return <section className="staff-limited"><h1>직원 관리</h1><p role="status">직원 목록을 불러오는 중…</p></section>;
 return <section className="pm-design-d staff-limited"><h1>직원 관리</h1><p>직원 {rows.length}명 · 운영 기능 권한 관리</p><input type="search" aria-label="직원 이름 검색" placeholder="직원 이름 검색" value={query} onChange={e => setQuery(e.target.value)} />{error && !rows.length && <><p role="alert">{error}</p><button className="staff-cap-refresh" onClick={() => void load()}>다시 불러오기</button></>}<StaffDirectory employees={rows.filter(r => r.name.includes(query.trim())).map(r => ({ id: r.id, name: r.name, summary: `${r.operation_role === 'owner' ? '최고 관리자' : r.operation_role === 'manager' ? '관리자' : r.operation_role === 'staff' ? '직원' : '운영 멤버십 없음'} · ${r.active ? '활성' : '비활성'}` }))}>{id => <><section className="staff-section"><h3>운영 설정</h3><p>{rows.find(r => r.id === id)?.operation_active ? '운영 접근 활성' : '운영 접근 비활성'}</p></section>{detail(id)}<PaymentCapabilityManagement key={id} selectedId={id}/></>}</StaffDirectory>{loading && <p role="status">직원 목록을 불러오는 중…</p>}</section>;
}
