// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {MemoryRouter,useLocation,useNavigate} from 'react-router-dom';
import {readFileSync} from 'node:fs';
import App from '../App';
import {RequestQuickAction,canLaunchRequest} from './RequestLauncher';
import {ModuleProvider} from '../app/ModuleContext';
import {markModuleGateComplete} from '../app/moduleState';
import {NotificationProvider} from '../notifications/NotificationProvider';
import {emptyInbox,notificationRepository,type Notice} from '../notifications/notificationRepository';
import {TaskWorkspace} from './TaskRequestsPage';
import {taskRequestRepository,type TaskRequest} from './taskRequestRepository';
const state=vi.hoisted(()=>({loading:false,access:{enabled:true,loading:false,can_create:false,owner:false},detail:vi.fn(),list:vi.fn()}));
const identity=vi.hoisted(()=>({user:{id:'self'},profile:{id:'self',role:'staff',name:'직원',isActive:true,accountStatus:'active'}}));
vi.mock('../auth/AuthContext',()=>({useAuth:()=>({...identity,loading:state.loading})}));
vi.mock('../lib/supabase',()=>({supabase:{}}));
vi.mock('./useTaskAccess',()=>({useTaskAccess:()=>state.access}));
vi.mock('../notifications/webPushClient',()=>({webPushEnabled:false}));
const task:TaskRequest={id:'task-one',requester_id:'self',requester_name:'요청자',title:'점검 요청',body:'업무 내용',due_at:'2099-10-07T00:00:00Z',created_at:'2026-10-05T00:00:00Z',cancelled_at:null,cancel_reason:null,version:1,can_cancel:false,targets:[{recipient_id:'self',name:'직원',acknowledged_at:null,completed_at:null,completion_note:null,version:1}]};
function Observe(){const l=useLocation(),n=useNavigate();return <><output aria-label="경로">{l.pathname+l.search}</output><button onClick={()=>n(-1)}>history back</button></>;}
const root=(path='/select-module')=><MemoryRouter initialEntries={[path]}><ModuleProvider><NotificationProvider enabled><Observe/><App/></NotificationProvider></ModuleProvider></MemoryRouter>;
beforeEach(()=>{localStorage.clear();sessionStorage.clear();state.loading=false;state.access={enabled:true,loading:false,can_create:false,owner:false};vi.spyOn(taskRequestRepository,'list').mockResolvedValue([task]);vi.spyOn(taskRequestRepository,'detail').mockResolvedValue(task);vi.spyOn(taskRequestRepository,'recipients').mockResolvedValue([]);vi.spyOn(notificationRepository,'inbox').mockResolvedValue({...emptyInbox,items:[{id:'n',category:'TASK_REQUEST',deep_link_type:'TASK_REQUEST',deep_link_id:task.id,title:'새 업무요청이 도착했습니다.',message:'',created_at:task.created_at,priority:'NORMAL',ack_required:false} as Notice]});vi.spyOn(notificationRepository,'subscribe').mockReturnValue(()=>{});vi.spyOn(notificationRepository,'read').mockResolvedValue();});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('Module Gate task notification uses SPA target and has no nested dialog',async()=>{render(root());fireEvent.click(await screen.findByRole('button',{name:/알림센터, 읽지 않은/}));fireEvent.click(await screen.findByRole('button',{name:/새 업무요청이 도착/}));await screen.findByText('점검 요청');expect(screen.getByLabelText('경로').textContent).toBe('/operations/requests?scope=inbox&filter=active&task=task-one');expect(screen.queryByRole('dialog')).toBeNull();expect(screen.queryByRole('button',{name:'+ 요청'})).toBeNull();});
it('restored session on cold detail URL retains exact intent and foreground keeps it',async()=>{markModuleGateComplete('self');state.loading=true;const view=render(root('/operations/requests?scope=sent&filter=all&task=task-one'));state.loading=false;view.rerender(root('/operations/requests?scope=sent&filter=all&task=task-one'));await screen.findByText('점검 요청');fireEvent.focus(window);fireEvent(document,new Event('visibilitychange'));expect(screen.getByLabelText('경로').textContent).toContain('scope=sent&filter=all&task=task-one');});
it('cold unfinished gate preserves task intent through explicit Operations selection',async()=>{render(root('/operations/requests?task=task-one'));await screen.findByText('스케줄 관리');fireEvent.click(screen.getByRole('button',{name:/스케줄 관리/}));await screen.findByText('점검 요청');expect(screen.getByLabelText('경로').textContent).toBe('/operations/requests?task=task-one');});
it('sidebar task menu precedes staff without reordering other menus',()=>{const app=readFileSync('src/App.tsx','utf8');expect(app.indexOf('to: "/operations/requests"')).toBeLessThan(app.indexOf('to: "/operations/staff"'));expect(app).toContain('<Route path="requests" element={<TaskRequestsPage />} />');});
it.each([false,true])('owner=%s alone determines all tab, create controls compose independently',async owner=>{state.access.owner=owner;state.access.can_create=!owner;markModuleGateComplete('self');render(root('/operations/requests'));await screen.findByText('점검 요청');expect(!!screen.queryByRole('button',{name:'전체 현황'})).toBe(owner);expect((screen.queryAllByRole('button',{name:'+ 요청'}).length>0)).toBe(!owner);});
it('forged all scope by non-owner never requests all data',async()=>{render(<MemoryRouter initialEntries={['/operations/requests?scope=all']}><TaskWorkspace userId="self" access={state.access} revision={0}/></MemoryRouter>);await waitFor(()=>expect(taskRequestRepository.list).toHaveBeenCalledWith('inbox',0,'active'));expect(taskRequestRepository.list).not.toHaveBeenCalledWith('all',0,'active');});
it('sent/filter/pagination context survives detail back and browser history',async()=>{render(<MemoryRouter initialEntries={['/operations/requests?scope=sent&filter=all&offset=50']}><Observe/><TaskWorkspace userId="self" access={state.access} revision={0}/></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:/점검 요청/}));await screen.findByRole('heading',{name:'점검 요청'});fireEvent.click(screen.getByRole('button',{name:'목록으로'}));await screen.findByRole('button',{name:/점검 요청/});expect(screen.getByLabelText('경로').textContent).toBe('/operations/requests?scope=sent&filter=all&offset=50');fireEvent.click(screen.getByRole('button',{name:'history back'}));await screen.findByRole('heading',{name:'점검 요청'});});
it('navigation sources do not perform document navigation or keep TaskHub',()=>{for(const f of ['src/notifications/NotificationUi.tsx','src/taskRequests/TaskHomeEntry.tsx','src/taskRequests/TaskRequestsPage.tsx']){const s=readFileSync(f,'utf8');expect(s).not.toMatch(/window.location|location.assign|TaskHub/);}});

it('legacy route replaces without adding a history entry and preserves query/hash',async()=>{
 markModuleGateComplete('self');render(<MemoryRouter initialEntries={['/select-module','/operations/tasks?scope=sent&filter=all&task=task-one#context']} initialIndex={1}><ModuleProvider><NotificationProvider enabled><Observe/><App/></NotificationProvider></ModuleProvider></MemoryRouter>);
 await screen.findByText('점검 요청');expect(screen.getByLabelText('경로').textContent).toBe('/operations/requests?scope=sent&filter=all&task=task-one');fireEvent.click(screen.getByText('history back'));await screen.findByText('스케줄 관리');expect(screen.getByLabelText('경로').textContent).toBe('/select-module');
});
it('quick action opens once and closing preserves originating route',async()=>{
 state.access.can_create=true;render(<MemoryRouter initialEntries={['/operations/today?date=2026-10-06']}><Observe/><RequestQuickAction/></MemoryRouter>);
 const button=screen.getByRole('button',{name:'+ 요청'});fireEvent.click(button);fireEvent.click(button);expect(screen.getAllByRole('dialog')).toHaveLength(1);await screen.findByLabelText('제목');fireEvent.click(screen.getByRole('button',{name:'닫기'}));expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByLabelText('경로').textContent).toBe('/operations/today?date=2026-10-06');
});
it.each([false,true])('owner %s without create has no launcher',owner=>{state.access.owner=owner;render(<MemoryRouter><RequestQuickAction/></MemoryRouter>);expect(screen.queryByRole('button',{name:'+ 요청'})).toBeNull();expect(canLaunchRequest({...state.access,enabled:false,can_create:true})).toBe(false);});
it('Request page uses same single composer and empty received/sent states',async()=>{
 state.access.can_create=true;vi.mocked(taskRequestRepository.list).mockResolvedValue([]);render(<MemoryRouter><TaskWorkspace userId="self" access={state.access} revision={0}/></MemoryRouter>);
 await screen.findByText('받은 요청이 없습니다.');fireEvent.click(screen.getByRole('button',{name:'보낸 요청'}));await screen.findByText('보낸 요청이 없습니다.');fireEvent.click(screen.getByRole('button',{name:'+ 요청'}));expect(screen.getAllByRole('dialog')).toHaveLength(1);await screen.findByLabelText('제목');fireEvent.click(screen.getByRole('button',{name:'닫기'}));expect(screen.getByRole('button',{name:'보낸 요청'}).getAttribute('aria-pressed')).toBe('true');
});
it('mobile quick action stays outside crowded header and payment placeholders do not exist',()=>{const css=readFileSync('src/taskRequests/taskRequests.css','utf8');expect(css).toContain('.pt-request-quick{display:none}');expect(css).toContain('@media(min-width:1024px)');const launcher=readFileSync('src/taskRequests/RequestLauncher.tsx','utf8');expect(launcher).not.toMatch(/PAYMENT_|결제/);});

it.each(['/operations/today','/operations/calendar','/operations/hotel','/operations/customers','/operations/customer-management','/operations/staff'])('other Operations route %s keeps exactly one global CTA',path=>{state.access.can_create=true;render(<MemoryRouter initialEntries={[path]}><RequestQuickAction/></MemoryRouter>);expect(screen.getAllByRole('button',{name:'+ 요청'})).toHaveLength(1);});
it.each(['/operations/requests','/operations/requests/','/operations/tasks','/operations/tasks/'])('hub or legacy %s suppresses global CTA before redirect',path=>{state.access.can_create=true;render(<MemoryRouter initialEntries={[path+'?scope=sent#context']}><RequestQuickAction/></MemoryRouter>);expect(screen.queryByRole('button',{name:'+ 요청'})).toBeNull();});
it.each(['/operations/requests','/operations/tasks'])('rendered hub from %s has one page CTA and one composer after rapid clicks',async path=>{state.access.can_create=true;markModuleGateComplete('self');render(root(path));await screen.findByText('점검 요청');expect(screen.getByLabelText('경로').textContent).toBe('/operations/requests');expect(document.querySelector('.pt-request-quick')).toBeNull();const ctas=screen.getAllByRole('button',{name:'+ 요청'});expect(ctas).toHaveLength(1);fireEvent.click(ctas[0]);fireEvent.click(ctas[0]);expect(screen.getAllByRole('dialog')).toHaveLength(1);await screen.findByLabelText('제목');});
