// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {TaskComposer} from './TaskRequestUi';
import {taskRequestRepository} from './taskRequestRepository';
import {pendingTaskCreates} from './taskAttempts';
import {taskDue} from './taskRequestPresentation';
vi.mock('../lib/supabase',()=>({supabase:{rpc:vi.fn()}}));
afterEach(()=>{cleanup();pendingTaskCreates.clear();});
const setup=()=>{const repository={...taskRequestRepository,recipients:vi.fn(async()=>[{id:'one',name:'이화인'},{id:'two',name:'최석현'}]),create:vi.fn(async()=>'created')};const view=render(<TaskComposer repository={repository} onCreated={()=>{}}/>);return {repository,...view};};
async function open(){fireEvent.focus(screen.getByPlaceholderText('이름으로 담당자 검색'));await screen.findByRole('checkbox',{name:'이화인'});}
function fill(due='2099-10-07T00:30'){fireEvent.change(screen.getByLabelText('제목'),{target:{value:'업무'}});fireEvent.change(screen.getByLabelText('내용'),{target:{value:'내용'}});fireEvent.change(screen.getByLabelText('완료기한'),{target:{value:due}});}
function submit(){fireEvent.submit(screen.getByRole('button',{name:'업무요청 보내기'}).closest('form')!);}
it('focus lists only canonical eligible recipients; search retains selection and chip removal',async()=>{setup();expect(screen.queryByRole('checkbox')).toBeNull();await open();expect(screen.getAllByRole('checkbox')).toHaveLength(2);expect(screen.queryByText('inactive')).toBeNull();fireEvent.click(screen.getByRole('checkbox',{name:'이화인'}));expect(screen.getByText('1명 선택')).toBeTruthy();const search=screen.getByPlaceholderText('이름으로 담당자 검색');fireEvent.change(search,{target:{value:'최'}});expect(screen.queryByRole('checkbox',{name:'이화인'})).toBeNull();fireEvent.click(screen.getByRole('checkbox',{name:'최석현'}));expect(screen.getByText('2명 선택')).toBeTruthy();fireEvent.change(search,{target:{value:''}});expect((screen.getByRole('checkbox',{name:'이화인'}) as HTMLInputElement).checked).toBe(true);fireEvent.click(screen.getByRole('button',{name:'이화인 선택 제거'}));expect((screen.getByRole('checkbox',{name:'이화인'}) as HTMLInputElement).checked).toBe(false);});
it('multi-select payload has unique canonical ids and KST due',async()=>{const {repository}=setup();await open();for(const name of ['이화인','최석현','이화인','이화인'])fireEvent.click(screen.getByRole('checkbox',{name}));fill();submit();await waitFor(()=>expect(repository.create).toHaveBeenCalledTimes(1));expect(repository.create.mock.calls[0]).toEqual([expect.objectContaining({recipientIds:['two','one'],dueAt:'2099-10-06T15:30:00.000Z'})]);});
it('empty recipient and past due block RPC',async()=>{const {repository}=setup();fill();submit();expect(screen.getByRole('alert').textContent).toBe('담당자를 선택해주세요.');await open();fireEvent.click(screen.getByRole('checkbox',{name:'이화인'}));fill('2020-10-06T12:30');submit();expect(screen.getByRole('alert').textContent).toBe('완료기한은 현재보다 이후로 설정해주세요.');expect(repository.create).not.toHaveBeenCalled();});
it('new, reopened, and post-success composer have no actual due default',async()=>{let view=setup();expect((screen.getByLabelText('완료기한') as HTMLInputElement).value).toBe('');fill();view.unmount();view=setup();expect((screen.getByLabelText('완료기한') as HTMLInputElement).value).toBe('');await open();fireEvent.click(screen.getByRole('checkbox',{name:'이화인'}));fill();submit();await waitFor(()=>expect(view.repository.create).toHaveBeenCalledTimes(1));view.unmount();setup();expect((screen.getByLabelText('완료기한') as HTMLInputElement).value).toBe('');expect(screen.getByText(/미선택 · 완료기한/)).toBeTruthy();});
it('Escape closes only picker, Enter on search never submits',async()=>{const {repository}=setup();await open();const input=screen.getByPlaceholderText('이름으로 담당자 검색');fireEvent.keyDown(input,{key:'Escape'});expect(screen.queryByRole('checkbox')).toBeNull();fireEvent.keyDown(input,{key:'Enter'});expect(screen.getAllByRole('checkbox')).toHaveLength(2);expect(repository.create).not.toHaveBeenCalled();});
it('KST midnight and future validation do not invent missing time',()=>{expect(taskDue('2099-10-07T00:30',0)).toBe('2099-10-06T15:30:00.000Z');expect(taskDue('2099-10-06T23:30',0)).toBe('2099-10-06T14:30:00.000Z');expect(()=>taskDue('2099-10-07',0)).toThrow();expect(()=>taskDue('2099-10-07T00:30',Date.parse('2099-10-06T15:30Z'))).toThrow();});

it('row mousedown preserves focus until native click; Enter toggles once without submit',async()=>{const {repository}=setup();await open();const checkbox=screen.getByRole('checkbox',{name:'이화인'});const row=checkbox.closest('label')!;const down=new MouseEvent('mousedown',{bubbles:true,cancelable:true});fireEvent(row,down);expect(down.defaultPrevented).toBe(true);fireEvent.click(checkbox);expect(screen.getByText('1명 선택')).toBeTruthy();fireEvent.keyDown(checkbox,{key:'Enter'});expect(screen.queryByText('1명 선택')).toBeNull();expect(repository.create).not.toHaveBeenCalled();});
it('fresh due has explicit empty text presentation; native editor only on focus and empty blur resets it',()=>{setup();const due=screen.getByLabelText('완료기한') as HTMLInputElement;expect(due.value).toBe('');expect(due.type).toBe('text');expect(due.placeholder).toBe('날짜와 시간을 선택해주세요');fireEvent.focus(due);expect(due.type).toBe('datetime-local');fireEvent.blur(due);expect(due.value).toBe('');expect(due.type).toBe('text');fill('2020-10-06T12:30');submit();expect(screen.getByRole('alert').textContent).toBe('완료기한은 현재보다 이후로 설정해주세요.');});
