-- Catalog-only capture. No application rows, credentials, or role passwords.
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL statement_timeout = '30s';
WITH scope AS (
 SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
 WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','S')
), manifest AS (SELECT jsonb_build_object(
 'format',1,'serverVersion',current_setting('server_version'),'readOnly',current_setting('transaction_read_only'),
 'extensions',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) ORDER BY e.extname),'[]') FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
 'relations',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'acl',c.relacl,'options',c.reloptions,'view',CASE WHEN c.relkind IN ('v','m') THEN pg_get_viewdef(c.oid,false) END,
 'columns',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated,'acl',a.attacl,'collation',CASE WHEN a.attcollation<>0 THEN a.attcollation::regcollation::text END) ORDER BY a.attnum),'[]') FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped)) ORDER BY c.relname),'[]') FROM pg_class c WHERE c.oid IN(SELECT oid FROM scope)),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',c.conrelid::regclass::text,'name',c.conname,'type',c.contype,'definition',pg_get_constraintdef(c.oid,false),'validated',c.convalidated,'reference',CASE WHEN c.confrelid<>0 THEN c.confrelid::regclass::text END) ORDER BY c.conrelid::regclass::text,c.conname),'[]') FROM pg_constraint c WHERE c.conrelid IN(SELECT oid FROM scope)),
 'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',i.indrelid::regclass::text,'name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'constraintOwned',EXISTS(SELECT 1 FROM pg_constraint k WHERE k.conindid=i.indexrelid)) ORDER BY ic.relname),'[]') FROM pg_index i JOIN pg_class ic ON ic.oid=i.indexrelid WHERE i.indrelid IN(SELECT oid FROM scope)),
 'functions',(SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'signature',p.oid::regprocedure::text,'identityArgs',pg_get_function_identity_arguments(p.oid),'return',pg_get_function_result(p.oid),'definition',pg_get_functiondef(p.oid),'body',p.prosrc,'bodyMd5',md5(p.prosrc),'owner',pg_get_userbyid(p.proowner),'securityDefiner',p.prosecdef,'config',p.proconfig,'volatility',p.provolatile,'kind',p.prokind,'acl',p.proacl) ORDER BY n.nspname,p.oid::regprocedure::text),'[]') FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE (n.nspname='public' OR (n.nspname='auth' AND p.proname IN('uid','role','jwt','email'))) AND p.prokind IN('f','p') AND NOT EXISTS(SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.deptype='e')),
 'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'name',t.tgname,'definition',pg_get_triggerdef(t.oid,false),'function',t.tgfoid::regprocedure::text,'enabled',t.tgenabled) ORDER BY t.tgrelid::regclass::text,t.tgname),'[]') FROM pg_trigger t WHERE NOT t.tgisinternal AND (t.tgrelid IN(SELECT oid FROM scope) OR t.tgfoid IN(SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'))),
 'policies',(SELECT coalesce(jsonb_agg(jsonb_build_object('table',p.polrelid::regclass::text,'name',p.polname,'command',p.polcmd,'permissive',p.polpermissive,'roles',(SELECT jsonb_agg(CASE WHEN r=0 THEN 'public' ELSE pg_get_userbyid(r) END ORDER BY r) FROM unnest(p.polroles) r),'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polrelid::regclass::text,p.polname),'[]') FROM pg_policy p WHERE p.polrelid IN(SELECT oid FROM scope)),
 'types',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',t.typname,'kind',t.typtype,'labels',(SELECT jsonb_agg(e.enumlabel ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid=t.oid)) ORDER BY t.typname),'[]') FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typtype IN('e','d')),
 'dependencies',(SELECT coalesce(jsonb_agg(jsonb_build_object('source',pg_describe_object(d.classid,d.objid,d.objsubid),'target',pg_describe_object(d.refclassid,d.refobjid,d.refobjsubid),'kind',d.deptype) ORDER BY d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid),'[]') FROM pg_depend d WHERE (d.classid='pg_proc'::regclass AND d.objid IN(SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public')) OR (d.classid='pg_class'::regclass AND d.objid IN(SELECT oid FROM scope)))
) AS catalog)
SELECT n AS chunk_number, md5(catalog::text) AS manifest_md5, length(catalog::text) AS total_length, substring(catalog::text FROM (n-1)*50000+1 FOR 50000) AS catalog_chunk FROM manifest CROSS JOIN LATERAL generate_series(1,ceil(length(catalog::text)/50000.0)::integer) n ORDER BY n;
ROLLBACK;
