BEGIN;
DO $$ BEGIN IF current_database()<>'dog_current_baseline' OR inet_server_addr() IS NOT NULL THEN RAISE EXCEPTION 'LOCAL_ONLY'; END IF; END $$;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000900',true);
CREATE FUNCTION pg_temp.f(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
DO $$ DECLARE j jsonb; sid uuid; cid uuid; oid uuid; v integer; sv integer; d date:=(now() AT TIME ZONE 'Asia/Seoul')::date; BEGIN
 j:=public.create_daycare_reservation(pg_temp.f(21),pg_temp.f(30),pg_temp.f(800),pg_temp.f(4),d-2,'09:00','18:00',pg_temp.f(40),pg_temp.f(53),ARRAY[pg_temp.f(900)],'Synthetic',gen_random_uuid());
 SELECT operation_schedule_id,version INTO sid,v FROM daycare_operation_states WHERE canonical_payload->>'dogId'=pg_temp.f(4)::text;
 PERFORM public.complete_daycare_check_in(sid,v,(d-2+'09:00'::time) AT TIME ZONE 'Asia/Seoul',gen_random_uuid());
 SELECT version INTO v FROM daycare_operation_states WHERE operation_schedule_id=sid;
 PERFORM public.complete_daycare_check_out(sid,v,(d-2+'17:00'::time) AT TIME ZONE 'Asia/Seoul',gen_random_uuid());
 RAISE NOTICE 'BASELINE_DAYCARE_PASS';
 sid:=public.create_sale_with_payments(jsonb_build_object('sale_date',d,'business_unit_id',pg_temp.f(10),'dog_id',pg_temp.f(5),'customer_id',pg_temp.f(800),'product_id',pg_temp.f(60),'original_amount',100,'quantity',1,'unit_price',100,'paid_amount',50,'customer_type','new','outstanding_amount',50,'business_unit_name','Synthetic Hotel','product_name','Synthetic Product'),jsonb_build_array(jsonb_build_object('payment_method','cash','amount',25),jsonb_build_object('payment_method','card','amount',25)));
 PERFORM public.add_sale_payment(sid,50,'cash',d,'Synthetic payment',gen_random_uuid());
 PERFORM public.record_sale_refund(sid,d,10,'Synthetic refund');
 RAISE NOTICE 'BASELINE_SALES_CREATE_PAYMENT_REFUND_PASS';
 j:=public.create_long_stay_contract(pg_temp.f(800),pg_temp.f(6),d-2,d+10,pg_temp.f(40),pg_temp.f(54),1000,1,'Synthetic',gen_random_uuid());
 cid:=(j->>'id')::uuid; v:=(j->>'version')::integer;
 PERFORM public.confirm_long_stay_month_v2(cid,v,date_trunc('month',d)::date,d-2,pg_temp.f(20),pg_temp.f(30),'09:00',false,pg_temp.f(40),pg_temp.f(54),ARRAY[pg_temp.f(900)],'Synthetic confirm',gen_random_uuid());
 j:=public.get_long_stay_contract(cid); v:=(j->>'version')::integer; sid:=(j->>'hotelStayId')::uuid;
 SELECT version INTO sv FROM hotel_stays WHERE id=sid;
 PERFORM public.complete_long_stay_check_in(cid,v,sv,(d-2+'09:00'::time) AT TIME ZONE 'Asia/Seoul','Synthetic arrival',gen_random_uuid());
 j:=public.get_long_stay_contract(cid); v:=(j->>'version')::integer;
 PERFORM public.start_long_stay_absence_v3(cid,v,(d-1+'09:00'::time) AT TIME ZONE 'Asia/Seoul',d-1,'15:00',false,'keep_room','Synthetic','Synthetic outing',gen_random_uuid());
 j:=public.get_long_stay_contract(cid); v:=(j->>'version')::integer;
 PERFORM public.complete_long_stay_absence_v2(cid,v,(d-1+'15:00'::time) AT TIME ZONE 'Asia/Seoul',NULL,'Synthetic','Synthetic return',gen_random_uuid());
 j:=public.get_long_stay_contract(cid); v:=(j->>'version')::integer; sid:=(j->>'hotelStayId')::uuid; SELECT version INTO sv FROM hotel_stays WHERE id=sid;
 PERFORM public.complete_long_stay_check_out(cid,v,sv,statement_timestamp(),'Synthetic checkout',gen_random_uuid());
 RAISE NOTICE 'BASELINE_LONG_STAY_CONFIRM_CHECKIN_OUTING_RETURN_CHECKOUT_PASS';
 j:=public.create_unassigned_shared_room_family_booking(pg_temp.f(800),'Synthetic',false,(SELECT jsonb_agg(jsonb_build_object('stableMemberKey','member-'||n,'dogId',pg_temp.f(n),'serviceType','hotel','assigneeIds',jsonb_build_array(pg_temp.f(900)),'sharedRoomGroupKey','synthetic-group','calendarId',pg_temp.f(20),'scheduleTypeId',pg_temp.f(30),'checkInDate',d-2,'checkInTime','09:00','checkOutDate',d+2,'checkOutTime','15:00','roomTypeId',pg_temp.f(40))) FROM generate_series(7,8) n),pg_temp.f(40),true,gen_random_uuid());
 cid:=(j->>'sharedRoomGroupId')::uuid;
 j:=public.create_shared_hotel_room_occupancy(cid,pg_temp.f(55),gen_random_uuid()); oid:=(j->>'id')::uuid;
 FOR sid IN SELECT (value->>'hotelStayId')::uuid FROM jsonb_array_elements(j->'members') LOOP
  v:=(public.get_shared_hotel_room_occupancy(oid)->>'version')::integer; SELECT version INTO sv FROM hotel_stays WHERE id=sid;
  PERFORM public.complete_shared_hotel_check_in(oid,sid,v,sv,(d-2+'10:00'::time) AT TIME ZONE 'Asia/Seoul',gen_random_uuid());
  v:=(public.get_shared_hotel_room_occupancy(oid)->>'version')::integer; SELECT version INTO sv FROM hotel_stays WHERE id=sid;
  PERFORM public.complete_shared_hotel_member_check_out(oid,sid,v,sv,statement_timestamp(),gen_random_uuid());
 END LOOP;
 PERFORM public.get_hotel_shared_room_history(d-2);
 RAISE NOTICE 'BASELINE_SHARED_REQUESTED_ALLOCATED_TWO_MEMBERS_COMPLETE_HISTORY_PASS';
 PERFORM public.register_journal_roster(d,ARRAY[pg_temp.f(1),pg_temp.f(9)],gen_random_uuid());
 SELECT id,version INTO sid,v FROM journal_entries WHERE dog_id=pg_temp.f(9);
 PERFORM public.update_journal_entry_draft_v2(sid,v,ARRAY['active'],true,false,NULL,ARRAY['daycare_food'],'loves_teacher','loves_friends',jsonb_build_array(jsonb_build_object('type','DOG','dogId',pg_temp.f(1))),NULL,NULL,NULL,NULL,'Synthetic happy day',gen_random_uuid());
 SELECT version INTO v FROM journal_entries WHERE id=sid; PERFORM public.complete_journal_entry(sid,v,gen_random_uuid());
 RAISE NOTICE 'BASELINE_JOURNAL_ROSTER_DRAFT_COMPLETE_PASS';
END $$;
ROLLBACK;
